import React, { useMemo } from 'react';
import { useLocation, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { 
  Download, Printer, Share2, ArrowLeft, 
  TrendingUp, MapPin, Calendar, Briefcase, 
  Globe, Target, Monitor, ShoppingBag 
} from "lucide-react";
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js';
import { Doughnut } from 'react-chartjs-2';

ChartJS.register(ArcElement, Tooltip, Legend);

const MIBBSResults = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const data = location.state?.questionnaireData;

  // --- LOGIC: CALCULATION OF BUDGETS (Based on screenshots) ---
  const calculatedBudgets = useMemo(() => {
    if (!data) return null;
    
    // Cleaning revenue string (e.g., "₹10,000" -> 10000)
    const revenue = parseInt(data.monthlyRevenue?.replace(/\D/g, '') || "0");
    
    // Example logic: Monthly budget is ~6% of revenue for FMCG/Early Stage
    const monthlyBudget = Math.round(revenue * 0.0598); 
    const annualBudget = monthlyBudget * 12;

    return {
      monthly: monthlyBudget,
      annual: annualBudget,
      digital: Math.round(annualBudget * 0.27),
      brand: Math.round(annualBudget * 0.21),
      traditional: Math.round(annualBudget * 0.22),
      events: Math.round(annualBudget * 0.30)
    };
  }, [data]);

  if (!data || !calculatedBudgets) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <button onClick={() => navigate("/")} className="bg-indigo-600 text-white px-6 py-2 rounded-lg flex items-center gap-2">
          <ArrowLeft size={18} /> No Data Found - Go Back
        </button>
      </div>
    );
  }

  // --- CHART DATA ---
  const chartData = {
    labels: ['Digital', 'Brand', 'Traditional', 'Events'],
    datasets: [{
      data: [27, 21, 22, 30],
      backgroundColor: ['#3b82f6', '#10b981', '#f59e0b', '#ef4444'],
      borderWidth: 0,
    }],
  };

  return (
    <div className="min-h-screen bg-[#F3F4F6] p-4 md:p-8 font-sans text-slate-800">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* ✅ HEADER SECTION */}
        <div className="bg-white p-6 rounded-xl border border-slate-200 flex flex-col md:flex-row justify-between items-center shadow-sm">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-indigo-600 rounded-lg flex items-center justify-center text-white font-bold text-2xl">M</div>
            <div>
              <h1 className="text-xl font-bold text-indigo-900 leading-none">Brand Budget Recommendation Report</h1>
              <p className="text-xs text-slate-500 mt-1 uppercase tracking-wider font-semibold">Generated by MIBBS - India's First Intelligent Brand Budgeting System</p>
            </div>
          </div>
          <div className="flex gap-2 mt-4 md:mt-0">
            <button className="p-2 bg-slate-100 rounded-lg text-slate-600 hover:bg-slate-200 transition-colors"><Printer size={20}/></button>
            <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg font-bold text-sm hover:bg-indigo-700 transition-all shadow-lg shadow-indigo-100">
              <Download size={18} /> DOWNLOAD PDF
            </button>
          </div>
        </div>

        {/* ✅ HERO BANNER */}
        <div className="bg-indigo-800 rounded-xl p-8 text-white text-center shadow-xl">
          <h2 className="text-xl font-bold uppercase tracking-widest mb-4">Why MIBBS?</h2>
          <p className="max-w-3xl mx-auto text-sm text-indigo-100 leading-relaxed">
            At Magsmen, we've seen brands struggle not because they lacked ideas, but because they lacked intelligent budget planning. 
            MIBBS is India's first intelligent brand budgeting system, a structured, data-driven model crafted to align your brand ambitions with financial discipline.
          </p>
        </div>

        {/* ✅ USER SUMMARY GRID */}
        <div className="bg-white rounded-xl p-8 border border-slate-200 shadow-sm relative overflow-hidden">
          <div className="flex justify-between items-center mb-6">
             <h3 className="text-2xl font-bold text-indigo-900 italic">{data.name}'s Marketing Plan</h3>
             <span className="flex items-center gap-1 text-emerald-500 font-bold text-sm bg-emerald-50 px-3 py-1 rounded-full border border-emerald-100 uppercase tracking-tighter">
               <TrendingUp size={14}/> {data.businessStage?.replace('_', ' ')}
             </span>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <InfoBox label="Industry" value={data.industry} icon={<Briefcase size={14}/>}/>
            <InfoBox label="Location" value={data.pincodeInfo?.district || data.pincode} icon={<MapPin size={14}/>}/>
            <InfoBox label="Years in Business" value={data.yearsInBusiness || "New Venture"} icon={<Calendar size={14}/>}/>
            <InfoBox label="Digital Maturity" value={data.digitalPresence} icon={<Monitor size={14}/>}/>
            <InfoBox label="Target Audience" value="Youth (18-35)" icon={<Users size={14}/>}/>
            <InfoBox label="Competition Level" value="Medium" color="text-red-500" icon={<TrendingUp size={14}/>}/>
            <InfoBox label="Marketing Goal" value={data.brandObjectives[0]?.replace('_', ' ')} color="text-purple-600" icon={<Target size={14}/>}/>
            <InfoBox label="Sales Channel" value={data.businessMode} color="text-emerald-600" icon={<ShoppingBag size={14}/>}/>
          </div>
        </div>

        {/* ✅ RECOMMENDED BUDGET CARDS */}
        <div className="space-y-4">
          <div className="bg-amber-50 border border-amber-100 rounded-xl p-4 text-center max-w-sm mx-auto shadow-sm">
             <p className="text-[10px] font-bold text-amber-600 uppercase tracking-widest mb-1">Estimated Monthly Revenue</p>
             <p className="text-2xl font-black text-amber-700">₹{data.monthlyRevenue || "10,000"}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-8 text-center shadow-sm">
              <p className="text-xs font-bold text-indigo-500 uppercase tracking-widest mb-2">Monthly Brand Budget</p>
              <h4 className="text-4xl font-black text-indigo-700">₹{calculatedBudgets.monthly.toLocaleString()}</h4>
            </div>
            <div className="bg-emerald-50 border border-emerald-100 rounded-2xl p-8 text-center shadow-sm">
              <p className="text-xs font-bold text-emerald-500 uppercase tracking-widest mb-2">Annual Budget (12 Months)</p>
              <h4 className="text-4xl font-black text-emerald-700">₹{calculatedBudgets.annual.toLocaleString()}</h4>
            </div>
          </div>
        </div>

        {/* ✅ BUDGET ALLOCATION & CHART SECTION */}
        <div className="bg-white rounded-xl p-8 border border-slate-200 shadow-sm">
          <h3 className="text-lg font-bold text-slate-800 mb-8 border-b pb-4">Budget Allocation & Channel Performance</h3>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Pie Chart */}
            <div className="relative w-full max-w-[300px] mx-auto">
              <Doughnut data={chartData} options={{ cutout: '75%', plugins: { legend: { display: false } } }} />
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className="text-3xl font-black text-slate-800">100%</span>
                <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Allocated</span>
              </div>
            </div>

            {/* Industry Focus Bars */}
            <div className="space-y-6">
               <h4 className="text-sm font-bold text-indigo-800 mb-4">Industry Channel Focus</h4>
               <ProgressBarRow label="TV" percent={17} value={1220} color="bg-indigo-500" />
               <ProgressBarRow label="Digital" percent={14} value={1005} color="bg-blue-500" />
               <ProgressBarRow label="Print" percent={23} value={1650} color="bg-purple-500" />
               <ProgressBarRow label="Mass Campaigns" percent={17} value={1220} color="bg-indigo-400" />
               <ProgressBarRow label="Brand Awareness" percent={20} value={1435} color="bg-blue-400" />
               <ProgressBarRow label="Retail Tie-Ups" percent={9} value={646} color="bg-indigo-300" />
            </div>
          </div>
        </div>

        {/* ✅ BOTTOM GRID ALLOCATION */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <AllocationCard title="Digital Marketing" percent={27} amount={calculatedBudgets.digital} color="border-blue-500" />
          <AllocationCard title="Brand & Creative" percent={21} amount={calculatedBudgets.brand} color="border-emerald-500" />
          <AllocationCard title="Traditional Media" percent={22} amount={calculatedBudgets.traditional} color="border-amber-500" />
          <AllocationCard title="Events & PR" percent={30} amount={calculatedBudgets.events} color="border-red-500" />
        </div>

        {/* ✅ FOOTER BANNER */}
        <div className="bg-indigo-800 rounded-xl p-8 text-white shadow-lg overflow-hidden relative">
          <div className="relative z-10">
            <h3 className="text-center font-bold text-lg mb-4 opacity-80 border-b border-indigo-400 pb-2">About Magsmen, Your Brand Consultants</h3>
            <p className="text-xs leading-relaxed text-indigo-100 text-center max-w-4xl mx-auto">
              Magsmen is a renowned brand consulting firm that helps businesses grow by making them easy to understand and trust. We believe every business has a unique story and we help you tell it in a simple and powerful way. We guide you to turn your business into a strong, well-known brand without complex ideas or inflated budgets.
            </p>
          </div>
          <div className="absolute top-0 right-0 p-4 opacity-5">
             <Rocket size={100}/>
          </div>
        </div>
        
        <p className="text-[10px] text-center text-slate-400 font-bold uppercase tracking-widest pb-10">
          © 2026 Magsmen. Secure. Private. In Your Control.
        </p>

      </div>
    </div>
  );
};

// --- SMALLER COMPONENTS ---

const InfoBox = ({ label, value, icon, color = "text-slate-800" }) => (
  <div className="bg-slate-50 p-3 rounded-lg border border-slate-100">
    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-tighter mb-1 flex items-center gap-1">
      {icon} {label}
    </p>
    <p className={`text-xs font-black ${color} capitalize truncate`}>{value}</p>
  </div>
);

const ProgressBarRow = ({ label, percent, value, color }) => (
  <div className="space-y-1">
    <div className="flex justify-between text-[10px] font-bold">
      <span className="text-slate-600 uppercase">{label}</span>
      <span className="text-indigo-900">{percent}% <span className="text-slate-400 ml-1">₹{value}</span></span>
    </div>
    <div className="w-full bg-slate-100 h-1.5 rounded-full">
      <div className={`${color} h-1.5 rounded-full transition-all duration-1000`} style={{ width: `${percent}%` }}></div>
    </div>
  </div>
);

const AllocationCard = ({ title, percent, amount, color }) => (
  <div className={`bg-white rounded-xl p-6 border-t-4 ${color} shadow-sm space-y-2`}>
    <div className="flex justify-between items-center">
      <h4 className="font-bold text-slate-800">{title}</h4>
      <span className="text-blue-600 font-black">{percent}%</span>
    </div>
    <h5 className="text-2xl font-black text-slate-900">₹{amount.toLocaleString()}</h5>
    <p className="text-[10px] text-slate-400 italic">Recommended annual budget for {title.toLowerCase()} activities.</p>
  </div>
);

const Rocket = ({ size }) => (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"/><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"/><path d="M9 12H4s.55-3.03 2-5c1.62-2.2 5-3 5-3"/><path d="M12 15v5s3.03-.55 5-2c2.2-1.62 3-5 3-5"/></svg>
);

const Users = ({ size }) => (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>
)

export default MIBBSResults;