
import React, { useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import html2pdf from 'html2pdf.js';

const Report = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const reportRef = useRef(null);
  const { answers } = location.state || {};

  if (!answers) {
    navigate('/');
    return null;
  }

  const industryMap: Record<string, string> = {
    technology: 'Technology',
    healthcare: 'Healthcare',
    retail: 'Retail',
    food: 'Food & Beverage',
    finance: 'Finance',
    education: 'Education',
    real_estate: 'Real Estate',
    other: 'Other'
  };

  const stageMap: Record<string, string> = {
    idea: 'Yet to Start',
    startup: 'Building Brand',
    scale: 'Scaling Brand'
  };

  const experienceMap: Record<string, string> = {
    '0': 'Just starting',
    '1-2': '1-2 years',
    '3-5': '3-5 years',
    '5+': '5+ years'
  };

  const budgetMap: Record<string, number> = {
    '10k-50k': 30000,
    '50k-2l': 100000,
    '2l+': 250000
  };

  const plannedBudget = budgetMap[answers?.budget?.[0]] || 100000;

  const allocations = [
    { label: 'LinkedIn Paid Ads for Brand Awareness (Tier 1 Cities)', amount: plannedBudget * 0.33 },
    { label: 'Industry Event Sponsorship (Local B2B Conference)', amount: plannedBudget * 0.28 },
    { label: 'Content Marketing (Whitepapers & Case Studies)', amount: plannedBudget * 0.22 },
    { label: 'Webinar Series on Brand Strategy', amount: plannedBudget * 0.11 },
    { label: 'Client Referral Incentives', amount: plannedBudget * 0.06 },
  ];

  const formatINR = (value: number) =>
    new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(value);

  const handleDownload = () => {
    const element = reportRef.current;
    if (element) {
      html2pdf()
        .from(element)
        .set({
          margin: 0.5,
          filename: 'Brand-Budget-Report.pdf',
          html2canvas: { scale: 2 },
          jsPDF: { unit: 'in', format: 'a4', orientation: 'portrait' }
        })
        .save();
    } else {
      alert('PDF generation failed. Content not found.');
    }
  };

  const handleStartOver = () => {
    navigate('/questionnaire');
  };

  return (
    <div className="bg-[#f6f6f6] min-h-screen px-4 py-8 text-gray-800 font-sans">

      {/* Report Content */}
      <div ref={reportRef} className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg p-6 print:p-8">
        <div className="text-center mb-6">
          <h1 className="text-2xl font-bold">Brand Budget Recommendation Report</h1>
          <p className="text-sm text-gray-500">Generated by MIBBS – India’s First Intelligent Brand Budgeting System</p>
          <hr className="mt-2 border-blue-500 w-32 mx-auto" />
        </div>

        {/* About MBIBS */}
        <div className="bg-[#1e1f51] text-white p-4 rounded mb-6 text-sm">
          <h2 className="text-lg font-semibold mb-2">About MIBBS</h2>
          <p>
            At Magmena, we have seen brands struggle — not because they lacked ideas, but because they lacked intelligent
            budget planning. In a market driven by intuition, we realized businesses needed more than just advice. They needed a system.
          </p>
          <p className="mt-2">
            A structured, intelligent model to align their brand ambitions with financial discipline. That’s why we built MIBBS —
            India’s first intelligent brand budgeting system, crafted to help businesses invest smarter, grow faster, and build
            stronger market positions.
          </p>
        </div>

        {/* Business Info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-[#f0f4ff] p-4 rounded mb-4 text-sm">
          <div>
            <p><strong>Location:</strong> {answers?.location?.[0] || 'N/A'}</p>
            <p><strong>Industry:</strong> {industryMap[answers?.industry?.[0]] || 'N/A'}</p>
            <p><strong>Business Type:</strong> {answers?.businessType?.[0] || 'B2B'}</p>
          </div>
          <div>
            <p><strong>Business Stage:</strong> {stageMap[answers?.stage?.[0]] || 'N/A'}</p>
            <p><strong>Years in Business:</strong> {experienceMap[answers?.experience?.[0]] || 'N/A'}</p>
            <p><strong>Planned Budget:</strong> {formatINR(plannedBudget)}</p>
          </div>
        </div>

        {/* Budget Bar */}
        <div className="bg-blue-600 text-white text-center font-bold py-2 rounded mb-6">
          Total Recommended Budget: {formatINR(plannedBudget)}
        </div>

        {/* Budget Summary */}
        <div className="mb-6">
          <h2 className="text-md font-semibold text-gray-700 mb-2">Budget Summary</h2>
          <p className="text-sm">
            This budget plan aims to heighten brand visibility and engagement among B2B businesses, directly aligning financial resources
            to areas with the highest potential impact.
          </p>
        </div>

        {/* Budget Allocation */}
        <div className="mb-6">
          <h2 className="text-md font-semibold text-gray-700 mb-2">Recommended Budget Allocation</h2>
          <div className="border rounded">
            {allocations.map((item, idx) => (
              <div key={idx} className="flex justify-between items-center p-3 border-b last:border-b-0 text-sm">
                <span>{item.label}</span>
                <span className="font-medium text-blue-700">
                  {((item.amount / plannedBudget) * 100).toFixed(1)}% ({formatINR(item.amount)})
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Strategic Recommendations */}
        <div className="mb-6">
          <h2 className="text-md font-semibold text-gray-700 mb-2">Strategic Recommendations</h2>
          <ul className="list-disc list-inside text-sm space-y-1 text-gray-700">
            <li>Deploy targeted ads to capture the attention of key decision-makers, ensuring Magmena remains top-of-mind.</li>
            <li>Leverage webinars and case studies to build industry authority.</li>
            <li>Sponsor relevant events to boost in-person visibility.</li>
          </ul>
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-gray-500 border-t pt-4">
          <p>Magmena is a renowned brand consulting firm that helps businesses grow by making them easy to understand and trust.</p>
          <p>Your data stays yours — always encrypted, never shared.</p>
          <p className="mt-2">Report Generated on: {new Date().toLocaleDateString()}</p>
        </div>
      </div>

      {/* Buttons: Only visible on screen, hidden in PDF */}
      <div className="flex justify-center gap-2 max-w-4xl mx-auto mt-4 print:hidden">
        <Button onClick={handleDownload} className="bg-[#5b2d89] text-white px-6 py-2 rounded">
          Download Report
        </Button>
        <Button onClick={handleStartOver} className="bg-gray-400 text-white px-6 py-2 rounded">
          Start Over
        </Button>
      </div>
    </div>
  );
};

export default Report;





































// import React from 'react';
// import { useLocation, useNavigate } from 'react-router-dom';
// import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
// import { Button } from '@/components/ui/button';
// import { ArrowLeft, MapPin, Building, Calendar, Target } from 'lucide-react';

// const Report = () => {
//   const location = useLocation();
//   const navigate = useNavigate();
//   // const answers = location.state?.answers || {};
//   const { answers, reportData } = location.state || {};
  

//   const getAnswerLabel = (questionId: string, answerId: string) => {
//     const labels: Record<string, Record<string, string>> = {
//       location: {
//         'mumbai': 'Mumbai',
//         'delhi': 'Delhi',
//         'bangalore': 'Bangalore',
//         'chennai': 'Chennai',
//         'pune': 'Pune',
//         'other': 'Other City'
//       },
//       industry: {
//         'technology': 'Technology',
//         'retail': 'Retail & E-commerce',
//         'healthcare': 'Healthcare',
//         'finance': 'Finance',
//         'food': 'Food & Beverage',
//         'education': 'Education',
//         'other': 'Other'
//       },
//       stage: {
//         'idea': 'Yet to start - Just an idea',
//         'startup': 'In business, looking to build brand',
//         'established': 'Established brand, want to scale'
//       },
//       experience: {
//         '0': 'Just starting',
//         '1-2': '1-2 years',
//         '3-5': '3-5 years',
//         '5+': '5+ years'
//       }
//     };
//     return labels[questionId]?.[answerId] || answerId;
//   };

//   const getIcon = (questionId: string) => {
//     const icons: Record<string, React.ReactNode> = {
//       location: <MapPin className="w-5 h-5" />,
//       industry: <Building className="w-5 h-5" />,
//       stage: <Target className="w-5 h-5" />,
//       experience: <Calendar className="w-5 h-5" />
//     };
//     return icons[questionId];
//   };

//   const getQuestionTitle = (questionId: string) => {
//     const titles: Record<string, string> = {
//       location: 'Business Location',
//       industry: 'Industry',
//       stage: 'Business Stage',
//       experience: 'Years in Business'
//     };
//     return titles[questionId] || questionId;
//   };

//   if (!answers || Object.keys(answers).length === 0) {
//     return (
//       <div className="min-h-screen bg-gray-50 flex items-center justify-center">
//         <Card className="w-full max-w-md">
//           <CardHeader>
//             <CardTitle>No Data Found</CardTitle>
//           </CardHeader>
//           <CardContent>
//             <p className="text-gray-600 mb-4">
//               No questionnaire data found. Please complete the questionnaire first.
//             </p>
//             <Button onClick={() => navigate('/questionnaire')} className="w-full">
//               Take Questionnaire
//             </Button>
//           </CardContent>
//         </Card>
//       </div>
//     );
//   }

//   return (
//     <div className="min-h-screen bg-gray-50 py-8">
//       <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
//         <div className="mb-8">
//           <Button
//             variant="outline"
//             onClick={() => navigate('/questionnaire')}
//             className="mb-4"
//           >
//             <ArrowLeft className="w-4 h-4 mr-2" />
//             Back to Questionnaire
//           </Button>
//           <h1 className="text-3xl font-bold text-gray-900 mb-2">
//             Your Brand Budget Analysis Report
//           </h1>
//           <p className="text-gray-600">
//             Based on your responses, here's your personalized analysis
//           </p>
//         </div>

//         <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
//           {Object.entries(answers).map(([questionId, answerIds]) => (
//             <Card key={questionId}>
//               <CardHeader className="pb-3">
//                 <CardTitle className="flex items-center space-x-2 text-lg">
//                   <div className="p-2 bg-purple-100 rounded-lg text-[#5b2d89]">
//                     {getIcon(questionId)}
//                   </div>
//                   <span>{getQuestionTitle(questionId)}</span>
//                 </CardTitle>
//               </CardHeader>
//               <CardContent>
//                 {Array.isArray(answerIds) && answerIds.map((answerId) => (
//                   <div key={answerId} className="text-gray-900 font-medium">
//                     {getAnswerLabel(questionId, answerId)}
//                   </div>
//                 ))}
//               </CardContent>
//             </Card>
//           ))}
//         </div>

//         <Card className="mb-8">
//           <CardHeader>
//             <CardTitle className="text-xl">Recommended Next Steps</CardTitle>
//           </CardHeader>
//           <CardContent>
//             <div className="space-y-4">
//               <div className="p-4 bg-blue-50 rounded-lg">
//                 <h3 className="font-semibold text-blue-900 mb-2">Budget Planning</h3>
//                 <p className="text-blue-800">
//                   Based on your business stage and industry, we recommend starting with a focused digital marketing approach.
//                 </p>
//               </div>
//               <div className="p-4 bg-green-50 rounded-lg">
//                 <h3 className="font-semibold text-green-900 mb-2">Agency Matching</h3>
//                 <p className="text-green-800">
//                   We can connect you with agencies that specialize in your industry and location.
//                 </p>
//               </div>
//               <div className="p-4 bg-purple-50 rounded-lg">
//                 <h3 className="font-semibold text-purple-900 mb-2">Tools & Resources</h3>
//                 <p className="text-purple-800">
//                   Use our free calculators to estimate costs for Facebook ads and website development.
//                 </p>
//               </div>
//             </div>
//           </CardContent>
//         </Card>

//         <div className="flex flex-col sm:flex-row gap-4">
//           <Button 
//             onClick={() => navigate('/agencies')}
//             className="bg-gradient-to-br from-[#ccadcc] to-[#5b2d89] hover:bg-[#5b2d89]"
//           >
//             Find Agencies
//           </Button>
//           <Button variant="outline" onClick={() => navigate('/tools')}>
//             Use Our Tools
//           </Button>
//           <Button variant="outline" onClick={() => navigate('/')}>
//             Back to Home
//           </Button>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default Report;

