import jsPDF from 'jspdf';

interface BudgetData {
  monthlyRevenue: number;
  annualBudget: number;
  industry: string;
  location: {
    city: string;
    state: string;
  };
  allocations: Array<{
    channel: string;
    percent: number;
    amount: number;
  }>;
  industryData?: {
    channels: string[];
    parameters: string[];
  };
  industryDetails?: {
    name: string;
    marketingSpendRange: string;
    channels: string[];
    parameters: string[];
  };
}

interface AssessmentData {
  brandStage?: string;
  yearsInBusiness?: number;
  digitalMaturity?: string;
}

export const generateBudgetPDF = async (budgetData: BudgetData, assessmentData: AssessmentData) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (2 * margin);
  let yPosition = margin;

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amount);
  };

  const addNewPageIfNeeded = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Header with gradient effect (simulated with rectangle)
  pdf.setFillColor(99, 102, 241); // Indigo
  pdf.rect(0, 0, pageWidth, 35, 'F');
  
  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Brand Budget Recommendation Report', pageWidth / 2, 15, { align: 'center' });
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by MIBBS - India\'s First Intelligent Brand Budgeting System', pageWidth / 2, 25, { align: 'center' });
  
  yPosition = 45;

  // About MIBBS Section
  pdf.setFillColor(238, 242, 255);
  pdf.roundedRect(margin, yPosition, contentWidth, 30, 3, 3, 'F');
  
  pdf.setTextColor(55, 65, 81);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('About MIBBS', margin + 5, yPosition + 8);
  
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  const aboutText = 'At Magsmen, we have seen brands struggle not because they lacked ideas, but because they lacked intelligent budget planning. MIBBS is India\'s first intelligent brand budgeting system, crafted to help businesses invest smarter, grow faster, and build stronger market positions.';
  const splitText = pdf.splitTextToSize(aboutText, contentWidth - 10);
  pdf.text(splitText, margin + 5, yPosition + 15);
  
  yPosition += 38;

  // Business Summary
  addNewPageIfNeeded(60);
  pdf.setFillColor(255, 255, 255);
  pdf.setDrawColor(229, 231, 235);
  pdf.roundedRect(margin, yPosition, contentWidth, 50, 3, 3, 'FD');
  
  pdf.setTextColor(17, 24, 39);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Business Summary', margin + 5, yPosition + 8);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  const summaryData = [
    ['Business Type:', assessmentData?.brandStage || 'growing'],
    ['Industry:', budgetData.industry],
    ['Location:', `${budgetData.location?.city}, ${budgetData.location?.state}`],
    ['Years in Business:', `${assessmentData?.yearsInBusiness || 1} years`],
    ['Digital Scale:', assessmentData?.digitalMaturity?.replace('-', ' ') || 'basic social'],
    ['Monthly Revenue:', formatCurrency(budgetData.monthlyRevenue || 0)]
  ];
  
  let summaryY = yPosition + 15;
  summaryData.forEach((item, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = margin + 5 + (col * (contentWidth / 2));
    const y = summaryY + (row * 10);
    
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(107, 114, 128);
    pdf.text(item[0], x, y);
    
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(17, 24, 39);
    pdf.text(item[1], x + 45, y);
  });
  
  yPosition += 58;

  // Monthly Budget Highlight
  addNewPageIfNeeded(35);
  pdf.setFillColor(99, 102, 241);
  pdf.roundedRect(margin, yPosition, contentWidth, 25, 3, 3, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  const monthlyBudget = formatCurrency((budgetData.monthlyRevenue || 0) * 0.05);
  pdf.text(monthlyBudget, pageWidth / 2, yPosition + 10, { align: 'center' });
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Monthly Brand Budget', pageWidth / 2, yPosition + 18, { align: 'center' });
  
  yPosition += 33;

  // Annual Budget
  addNewPageIfNeeded(15);
  pdf.setTextColor(55, 65, 81);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Total Annual Budget: ', pageWidth / 2 - 30, yPosition, { align: 'left' });
  
  pdf.setTextColor(99, 102, 241);
  pdf.setFontSize(12);
  pdf.text(formatCurrency((budgetData.monthlyRevenue || 0) * 0.05 * 12), pageWidth / 2 + 10, yPosition, { align: 'left' });
  
  yPosition += 15;

  // Budget Allocations
  addNewPageIfNeeded(80);
  pdf.setTextColor(17, 24, 39);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Budget Allocation', margin, yPosition);
  
  yPosition += 8;

  budgetData.allocations.forEach((allocation, index) => {
    addNewPageIfNeeded(25);
    
    const colors = [
      [139, 92, 246], // Purple
      [6, 182, 212],  // Cyan
      [245, 158, 11], // Amber
      [239, 68, 68]   // Red
    ];
    
    const color = colors[index % colors.length];
    
    // Card background
    pdf.setFillColor(249, 250, 251);
    pdf.setDrawColor(229, 231, 235);
    pdf.roundedRect(margin, yPosition, contentWidth, 20, 2, 2, 'FD');
    
    // Channel name
    pdf.setTextColor(17, 24, 39);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(allocation.channel, margin + 5, yPosition + 7);
    
    // Percentage badge
    pdf.setFillColor(color[0], color[1], color[2]);
    pdf.roundedRect(contentWidth - 10, yPosition + 3, 18, 8, 2, 2, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(10);
    pdf.text(`${allocation.percent}%`, contentWidth + 2, yPosition + 9, { align: 'center' });
    
    // Amount
    pdf.setTextColor(17, 24, 39);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text(formatCurrency(allocation.amount), margin + 5, yPosition + 15);
    
    yPosition += 23;
  });

  // Industry Insights
  if (budgetData.industryDetails) {
    yPosition += 5;
    addNewPageIfNeeded(60);
    
    pdf.setTextColor(17, 24, 39);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${budgetData.industryDetails.name} Industry Insights`, margin, yPosition);
    
    yPosition += 10;
    
    // Marketing Spend
    pdf.setFillColor(239, 246, 255);
    pdf.roundedRect(margin, yPosition, (contentWidth / 3) - 2, 20, 2, 2, 'F');
    pdf.setTextColor(55, 65, 81);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Marketing Spend', margin + 2, yPosition + 6);
    pdf.setTextColor(37, 99, 235);
    pdf.setFontSize(11);
    pdf.text(budgetData.industryDetails.marketingSpendRange, margin + 2, yPosition + 14);
    
    // Top Channels
    pdf.setFillColor(240, 253, 244);
    pdf.roundedRect(margin + (contentWidth / 3) + 1, yPosition, (contentWidth / 3) - 2, 20, 2, 2, 'F');
    pdf.setTextColor(55, 65, 81);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Top Channels', margin + (contentWidth / 3) + 3, yPosition + 6);
    pdf.setTextColor(22, 163, 74);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    const channels = budgetData.industryDetails.channels.slice(0, 2).join(', ');
    const channelText = pdf.splitTextToSize(channels, (contentWidth / 3) - 6);
    pdf.text(channelText, margin + (contentWidth / 3) + 3, yPosition + 12);
    
    // Key Focus
    pdf.setFillColor(250, 245, 255);
    pdf.roundedRect(margin + (2 * contentWidth / 3) + 2, yPosition, (contentWidth / 3) - 2, 20, 2, 2, 'F');
    pdf.setTextColor(55, 65, 81);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Key Focus', margin + (2 * contentWidth / 3) + 4, yPosition + 6);
    pdf.setTextColor(147, 51, 234);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    budgetData.industryDetails.parameters.slice(0, 2).forEach((param, index) => {
      pdf.text(`• ${param}`, margin + (2 * contentWidth / 3) + 4, yPosition + 12 + (index * 4));
    });
    
    yPosition += 25;
  }

  // Footer
  const footerY = pageHeight - 20;
  pdf.setFillColor(249, 250, 251);
  pdf.rect(0, footerY, pageWidth, 20, 'F');
  
  pdf.setTextColor(107, 114, 128);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text('About Magsmen', pageWidth / 2, footerY + 5, { align: 'center' });
  
  pdf.setFontSize(7);
  const footerText = 'Magsmen is a renowned brand consulting firm that helps businesses grow by making them easy to understand and trust.';
  const footerSplit = pdf.splitTextToSize(footerText, contentWidth - 20);
  pdf.text(footerSplit, pageWidth / 2, footerY + 10, { align: 'center' });
  
  pdf.setFontSize(6);
  pdf.setTextColor(156, 163, 175);
  pdf.text('Secure. Private. In Your Control. Your data stays yours — always encrypted, never shared.', pageWidth / 2, footerY + 17, { align: 'center' });

  // Save the PDF
  const filename = `MIBBS_Budget_Plan_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
};